In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("../data/preprocessed/stock_data/cipla.csv")
df2=pd.read_csv("../data/preprocessed/market_data/crudeoilfutures.csv")

In [3]:
df1.tail()

,Date,day_return_scaled,RSI,Sortino,MACD,emaslope_15d,tr,atr_15d,bb_width_15d,zscore_15d,ret_15d,max_dd_15d,vol_15d,sharpe_ratio_15,var95_15,cvar95_15,beta_15,alpha_5d,Target
735,2026-03-25,17.747668,53.060888,-0.525406,1.000655,3.033311,30.379228,12.116754,-17.297123,1.751712,-1.683640,-2.033419,185.296261,-0.218529,-16.982551,-24.121367,-0.040756,-2.191940,12.882225
736,2026-03-27,12.882225,55.942987,-0.353780,-0.397876,2.045967,4.865443,10.127354,-19.816103,1.274807,0.472942,-2.033419,190.594894,-0.190752,-16.982551,-24.121367,-0.032173,-2.067139,-5.685510
737,2026-03-30,-5.685510,43.699438,-0.558707,-0.007870,-0.530746,18.567735,10.535804,-18.828166,-0.260070,0.538677,-2.033419,191.008074,-0.200760,-16.982551,-24.121367,-0.031031,-2.134894,-47.091614
738,2026-04-01,-47.091614,34.649466,-0.581060,3.600830,-5.640166,41.406104,12.235002,-9.793515,-2.545811,-4.852683,-3.653397,253.044800,-0.385945,-31.012441,-47.091614,-0.085286,-0.056049,2.016827
739,2026-04-02,2.016827,49.691832,-0.588650,2.469642,1.203410,49.108441,15.223127,-9.052474,0.570926,-0.745880,-3.653397,248.075781,-0.417538,-31.012441,-47.091614,-0.089347,0.064163,NaN

In [4]:
df2.tail()

,Date,day_return_scaled,RSI,Sortino,MACD,emaslope_15d,tr,atr_15d,bb_width_15d,zscore_15d,ret_15d,max_dd_15d,vol_15d,sharpe_ratio_15,var95_15,cvar95_15,beta_15,alpha_5d
750,2026-03-27,67.838410,55.962135,0.098845,-4.458512,7.889536,33.914069,68.516202,106.124499,1.260609,-0.546137,-1.824064,829.470003,0.035612,-88.482327,-123.17187,0.061272,-1.423151
751,2026-03-30,2.729033,51.633951,0.141285,-3.198250,-1.235328,65.109377,60.694954,47.235117,-0.031540,-1.082800,-1.824064,815.194626,0.080014,-88.482327,-123.17187,0.062926,-2.307747
752,2026-03-31,-35.119468,47.845483,0.087559,0.844835,-5.811975,37.848500,62.809052,54.543638,-0.751903,0.309344,-1.824064,821.589718,0.069292,-88.482327,-123.17187,0.076038,-4.104324
753,2026-04-01,-15.729438,44.930470,-0.057070,2.456084,-2.661724,19.390029,62.037363,84.186816,-0.350005,-4.796468,-1.824064,825.466905,0.044892,-88.482327,-123.17187,0.074802,-3.550645
754,2026-04-02,127.577871,55.614205,0.119239,-7.741453,15.584405,143.307309,67.083096,38.023893,2.062399,0.777730,-1.824064,934.323642,0.099399,-88.482327,-123.17187,0.015310,-5.149388

In [5]:
df1.isnull().sum()

Date                 0
day_return_scaled    0
RSI                  0
Sortino              0
MACD                 0
emaslope_15d         0
tr                   0
atr_15d              0
bb_width_15d         0
zscore_15d           0
ret_15d              0
max_dd_15d           0
vol_15d              0
sharpe_ratio_15      0
var95_15             0
cvar95_15            0
beta_15              0
alpha_5d             0
Target               1
dtype: int64

In [47]:
df2.isnull().sum()

Date                 0
day_return_scaled    0
RSI                  0
Sortino              0
MACD                 0
emaslope_15d         0
tr                   0
atr_15d              0
bb_width_15d         0
zscore_15d           0
ret_15d              0
max_dd_15d           0
vol_15d              0
sharpe_ratio_15      0
var95_15             0
cvar95_15            0
beta_15              0
alpha_5d             0
dtype: int64

In [48]:
import numpy as np

In [49]:
mask = np.isinf(df1.select_dtypes(include=[np.number])).any(axis=1)
df1[mask]

Empty DataFrame
Columns: [Date, day_return_scaled, RSI, Sortino, MACD, emaslope_15d, tr, atr_15d, bb_width_15d, zscore_15d, ret_15d, max_dd_15d, vol_15d, sharpe_ratio_15, var95_15, cvar95_15, beta_15, alpha_5d]
Index: []

In [50]:
mask = np.isinf(df2.select_dtypes(include=[np.number])).any(axis=1)
df2[mask]

Empty DataFrame
Columns: [Date, day_return_scaled, RSI, Sortino, MACD, emaslope_15d, tr, atr_15d, bb_width_15d, zscore_15d, ret_15d, max_dd_15d, vol_15d, sharpe_ratio_15, var95_15, cvar95_15, beta_15, alpha_5d]
Index: []